/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"
#include <pthread.h>

struct arg_struct {		//χρησημοποιώντας την arg_struct τρέχω από το thread την ask1_1
    char * hostname;		// συνήθως localhost
    int client_name;
};

void ask1_1(void *arguments)
{
	struct arg_struct *args = arguments;
	CLIENT *clnt;
	float  *result_1; 	  //average value of an Y_array
	Y_array  avg_1_arg;
	max_min  *result_2; 	 //maximum and the minimum values of an Y_array
	Y_array  max_min_1_arg;
	aY  *result_3;  	//product of an Y_array
	prod_array  mul_1_arg;

#ifndef	DEBUG
	clnt = clnt_create ((char *)args->hostname, ASK1, ASK1_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (args->hostname);
		exit (1);
	}
#endif	/* DEBUG */
	
	int done = 0; 		//όταν done == 1 κλείνει το πρόγραμμα
	int choice;
	int i;
	int size;
	float a;	
	int *Y;		//διανυσμα Υ
	int client=(int) args->client_name;	//όνομα socket client


	do
	{
		recv(client,&choice,sizeof(int),0);	//λάβε την επιλογή από τον socket client
		
		printf("Choice from client: %d \n", choice);

		if(choice==1)		
		{
			
			//average value of Y[]
			
			recv(client,&size,sizeof(int),0);	//λάβε μέγεθος διανύσματος Y
		
			avg_1_arg.y_array.y_array_len=size;			//πέρνα το μέγεθος για τον rpc_server
			avg_1_arg.y_size=size;
			avg_1_arg.y_array.y_array_val= (int *) malloc(size*sizeof(int));
			Y = (int *) malloc(size*sizeof(int));
			
			recv(client,Y,size*sizeof(int),0);  //λάβε το διάνυσμα Y
			
			for(i=0;i<size;i++)
			{
				avg_1_arg.y_array.y_array_val[i] = Y[i];	//πέρνα το Y για τον rpc_server
			}
	
			result_1 = avg_1(&avg_1_arg, clnt);		//κάνει πράξεις στον rpc_server
			
			if (result_1 == (float *) NULL) 			//τσεκάρει αν πέτυχε το call
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				send(client,result_1,sizeof(float),0);	//στείλε τα αποτέσματα στον socket client
			}
			
		}
		else if(choice==2)
		{
			//maximum and the minimum values of a Y_array
			
			recv(client,&size,sizeof(int),0);		//λάβε μέγεθος διανύσματος Y
			
			max_min_1_arg.y_array.y_array_len=size;	//πέρνα το μέγεθος για τον rpc_server
			max_min_1_arg.y_size=size;
			max_min_1_arg.y_array.y_array_val= (int *) malloc(size*sizeof(int));
			Y = (int *) malloc(size*sizeof(int));
			
			recv(client,Y,size*sizeof(int),0);		//λάβε το διάνυσμα Y
			
			for(i=0;i<size;i++)
			{
				max_min_1_arg.y_array.y_array_val[i] = Y[i];	//πέρνα το Y για τον rpc_server
			}
						
			result_2 = max_min_1(&max_min_1_arg, clnt);		//υπολογίζει max τιμή και min τιμή του διανύσματος στον rpc_server
			
			if (result_2 == (max_min *) NULL) 					//τσεκάρει αμα πέτυχε το call
			{
				clnt_perror (clnt, "call failed");
			}
			else
			{
				send(client,result_2,2*sizeof(int),0);	        //στείλε τα αποτέσματα στον socket client
			}
			
		}		
		else if(choice==3)	
		{
			//product of an Y_array and a natural num
			
			recv(client,&size,sizeof(int),0);		//λάβε μέγεθος Y διανύσματος
			
			mul_1_arg.y_array.y_array_len=size;			//πέρνα το μέγεθος του Υ για τον rpc_server
			mul_1_arg.y_size=size;
			mul_1_arg.y_array.y_array_val= (int *) malloc(size*sizeof(int));
			Y = (int *) malloc(size*sizeof(int));
			
			recv(client,Y,size*sizeof(int),0);		//λάβε το διάνυσμα Y
			
			for(i=0;i<size;i++)
			{
				mul_1_arg.y_array.y_array_val[i] = Y[i];	//πέρνα το Y για τον rpc_server
			}
			
			
			recv(client,&a,sizeof(float),0);			//λάβε το a
			mul_1_arg.a = a;					//πέρνα το a για τον rpc_server
			
			result_3 = mul_1(&mul_1_arg, clnt);		//υπολογίζει a*Υ
			
			if (result_3 == (aY *) NULL) 
			{
				clnt_perror (clnt, "call failed");		//τσεκάρει άμα πέτυχε το call
			}
			else
			{
				send(client,result_3->prod.prod_val,size*sizeof(float),0);	//στείλε τα αποτέσματα στον socket client
			}			
		}
		else if(choice==4)	//έξοδος
		{
			done=1;
		}
		else
		{
			printf("Invalid Choice. Try Again.\n\n");
		}
	}while(!done);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int main (int argc, char *argv[])
{
	char *host;
	struct arg_struct arguments;	// arguments for passing in thread
	int input_socket;
	int accepted_socket;
	int portno;
	int clilen;
	int i=0;
	
	struct sockaddr_in serv_addr;
	struct sockaddr_in cli_addr;
	
	
	pthread_t thread[50];
	
	if (argc < 3) {		//πρότυπο χρήσης
        printf("usage %s hostname port\n", argv[0]);
        exit(1);
    }
	
	//προετοιμασία socket
	
	input_socket = socket(AF_INET, SOCK_STREAM, 0);	
	
	bzero((char *) &serv_addr, sizeof(serv_addr));
	
	
	portno = atoi(argv[2]);
	
	serv_addr.sin_family=AF_INET;
	serv_addr.sin_port=htons(portno);
	serv_addr.sin_addr.s_addr=INADDR_ANY;
	
	bind(input_socket, (struct sockaddr *) &serv_addr, sizeof(serv_addr));
	
	listen(input_socket,5);
	
	
	while(1)
	{
		
		printf("Waiting for connection...\n");
		clilen=sizeof(cli_addr);
		accepted_socket=accept(input_socket, (struct sockaddr *) &cli_addr, &clilen);	//εισοδος νεου client
		
		arguments.client_name = accepted_socket;
		arguments.hostname = argv[1];
		
		pthread_create(&(thread[i++]), NULL, (void *)ask1_1, (void *) &arguments);	//καλεσμα μεσω thread της ask1_1
	}


	return 0;
	
	exit (0);
}
