/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "ask1.h"

bool_t
xdr_Y_array (XDR *xdrs, Y_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y_array.y_array_val, (u_int *) &objp->y_array.y_array_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y_size))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_prod_array (XDR *xdrs, prod_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->y_array.y_array_val, (u_int *) &objp->y_array.y_array_len, 100,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->y_size))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->a))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_max_min (XDR *xdrs, max_min *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_aY (XDR *xdrs, aY *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->prod.prod_val, (u_int *) &objp->prod.prod_len, 100,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}
