/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"
#include <limits.h>		//for the initiale values of max,min  

float * avg_1_svc(Y_array *argp, struct svc_req *rqstp)
{
	static float  result;
	int i,sum=0;
	
	printf("Average function of Y called...\n");
	
	for(i=0;i<argp->y_size;i++)
		sum += argp->y_array.y_array_val[i];
		
	if(argp->y_size != 0){
		result = (float) sum/argp->y_size;
		printf("Average: %f\n",result);
	}
	else{
		result=0;
		printf("Could not compute the average because the size of the array is 0\n");
	}
	return &result;
}

max_min * max_min_1_svc(Y_array *argp, struct svc_req *rqstp)
{
	static max_min  result;
	int i;
	result.max = INT_MIN;
	result.min = INT_MAX;
	
	printf("Max min function of Y called...\n");
	
	for(i=0;i<argp->y_size;i++)
	{
		if(result.max < argp->y_array.y_array_val[i])
			result.max = argp->y_array.y_array_val[i];
		if(result.min > argp->y_array.y_array_val[i])	
			result.min = argp->y_array.y_array_val[i];
	}
	printf("max: %d min: %d\n",result.max,result.min);
	return &result;
}

aY * mul_1_svc(prod_array *argp, struct svc_req *rqstp)
{
	static aY  result;
	int i;
	
	printf("a*Y[] function called...\n");
	
	result.prod.prod_len=argp->y_size;
	result.prod.prod_val=(float *)malloc(argp->y_size*sizeof(float));
		
	for(i=0;i<argp->y_size;i++){
		result.prod.prod_val[i] = argp->a * argp->y_array.y_array_val[i];
		printf("a*Y[%d]=%f\n",i,result.prod.prod_val[i]);
		}
	return &result;
}
